export interface StateSinkCodegenInput {
  readonly modulePath: string;
  readonly exportName: string;
  readonly sink: {
    readonly kind: "checked-state-sink";
    readonly collection: {
      readonly name: string;
      readonly type: string;
      readonly primaryKey: string;
    };
  };
}

export function generateStateSinkModule(input: StateSinkCodegenInput): string {
  const typePrefix = pascalCase(input.exportName);
  const relativeModule = input.modulePath.replaceAll("\\", "/");
  return `// Generated by @streamsy/tanstack-db. DO NOT EDIT.
// Source: ${relativeModule}#${input.exportName}
import { createStateSchema } from "@durable-streams/state";
import { createStateSinkBinding } from "@streamsy/tanstack-db";
import type { ErrorOf, KeyOf, ParamsOf, RowOf, StatusOf } from "@streamsy/sinks";
import { Schema } from "effect";
import { ${input.exportName} } from "${relativeModule}";

export type ${typePrefix}Row = RowOf<typeof ${input.exportName}>;
export type ${typePrefix}Key = KeyOf<typeof ${input.exportName}>;
export type ${typePrefix}Params = ParamsOf<typeof ${input.exportName}>;
export type ${typePrefix}Error = ErrorOf<typeof ${input.exportName}>;
export type ${typePrefix}Status = StatusOf<typeof ${input.exportName}>;

export const ${input.exportName}Collections = createStateSchema({
  ${input.sink.collection.name}: {
    schema: Schema.toStandardSchemaV1(${input.exportName}.from.schema),
    type: ${input.exportName}.collection.type,
    primaryKey: ${input.exportName}.collection.primaryKey,
  },
});

export const ${input.exportName}Binding = createStateSinkBinding<
  ${typePrefix}Row,
  ${typePrefix}Params,
  typeof ${input.exportName}Collections
>({
  name: ${input.exportName}.name,
  route: ${input.exportName}.compiledRoute,
  protocolVersion: ${input.exportName}.protocol.sessionVersion,
  contractFingerprint: ${input.exportName}.fingerprint,
  state: ${input.exportName}Collections,
  collection: { ...${input.exportName}.collection, name: "${input.sink.collection.name}" as const },
});
`;
}

function pascalCase(value: string): string {
  return value
    .split(/[^a-zA-Z0-9]+/)
    .filter((part) => part.length > 0)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join("");
}
